version: '3'
services:
    memory_front:
        build: app/front
        container_name: memory_front
        ports:
            - "3000:80"

    memory_back:
        build: app/back
        container_name: memory_back
        environment:
            NODE_ENV: production
        ports:
            - "3333:3333"
        volumes:
            - ./data/back:/data
