version: '3'
services:
    memory_front:
        build:
            context: app/front
            args:
                api_url: "http://192.168.0.1:3333"
        container_name: memory_front
        ports:
            - "3000:80"

    memory_back:
        build: app/back
        container_name: memory_back
        ports:
            - "3333:3333"
        volumes:
            - ./data/back:/data
